spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/onmyoji?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true

server:
  port: 80
